@echo off
echo Building Machine Panel App...
echo Installing required libraries...
pip install pyinstaller customtkinter requests
echo Compiling the application...
pyinstaller --noconfirm --onedir --windowed --name "Panel_Maszyny" "main.py"
echo Build complete! The executable is ready inside the "dist\Panel_Maszyny" folder!
pause
